import os
import re
import logging
import argparse
from abc import ABC, abstractmethod
from datetime import datetime

from pyspark.sql import SparkSession
from pyspark.sql.functions import udf, col
from pyspark.sql.types import MapType, StringType

# ============================================================
# Logger
# ============================================================
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# ============================================================
# Base Extractor
# ============================================================
class BaseExtractor(ABC):
    @abstractmethod
    def extract(self, text: str) -> dict:
        pass


# ============================================================
# CY Extractor
# ============================================================
class CYExtractor(BaseExtractor):
    """Extracts broker, carrier, pickup, and delivery data from Coyote Logistics
    load confirmation text files generated by pymupdf4llm (Markdown format)."""

    def _normalize(self, text: str) -> str:
        if not text:
            return ""
        text = re.sub(r"\*{1,2}", "", text)
        text = re.sub(r"[ \t\u00A0]+", " ", text)
        text = re.sub(r"\r\n?", "\n", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = "\n".join([ln.strip() for ln in text.splitlines() if ln.strip()])
        return text.strip()

    def _parse_datetime(self, date_str: str, time_str: str) -> str:
        if not date_str or not time_str:
            return ""
        time_str = re.sub(r"^(at|from)\s*", "", time_str.strip())
        for fmt in ["%m/%d/%Y %H:%M", "%m/%d/%Y %I:%M %p"]:
            try:
                return datetime.strptime(f"{date_str} {time_str}", fmt).strftime("%Y-%m-%dT%H:%M:%S")
            except ValueError:
                continue
        return ""

    def _extract_stop_blocks(self, text: str) -> list:
        """Split text into stop blocks by 'Stop N: Pick Up' or 'Stop N: Delivery'."""
        markers = list(re.finditer(r"Stop\s+\d+\s*:\s*(Pick\s*Up|Delivery)", text, re.I))
        blocks = []
        for i, m in enumerate(markers):
            end = markers[i + 1].start() if i + 1 < len(markers) else len(text)
            sub = text[m.end():end]
            cutoff = re.search(r"\n#+\s*Charges\b|\nCharges\b", sub, re.I)
            if cutoff:
                sub = sub[:cutoff.start()]
            stop_type = "pickup" if "pick" in m.group(1).lower() else "delivery"
            blocks.append((stop_type, sub.strip()))
        return blocks

    def _extract_address_block(self, block: str) -> str:
        """Return text from Address label to the next major label (Contact, Phone, etc.).
        This sub-block is shared between address, city, state, zip extraction."""
        m = re.search(r"^Address\s+", block, re.I | re.M)
        if not m:
            return ""
        sub = block[m.start():]
        stop = re.search(
            r"\n(Contact|Phone|SLIC|Driver Work|Scheduled|Appointment|Commodity|Confirmation Numbers)\b",
            sub, re.I
        )
        return sub[:stop.start()] if stop else sub

    def _extract_facility(self, block: str) -> str:
        """Extract facility name — 'Facility Notes' occurrences are skipped."""
        for m in re.finditer(r"^Facility\s+(.+)$", block, re.I | re.M):
            value = m.group(1).strip()
            if value.lower() != "notes":
                return value
        return ""

    def _extract_address(self, block: str) -> str:
        """Extract street address lines only, stopping before the city/state/zip line."""
        addr_block = self._extract_address_block(block)
        if not addr_block:
            return ""
        m = re.search(r"^Address\s+(.+)$", addr_block, re.I | re.M)
        if not m:
            return ""
        parts = [m.group(1).strip()]
        for line in addr_block[m.end():].split("\n"):
            stripped = line.strip()
            if not stripped:
                continue
            # Stop at city/state pattern (e.g. "Clewiston, FL 33440")
            if re.search(r"[A-Za-z][A-Za-z ]+,\s*[A-Z]{2}", stripped):
                break
            parts.append(stripped)
        return " ".join(parts).strip()

    def _extract_city_state_zip(self, block: str) -> tuple:
        """Extract city, state, and zip.
        Searches line by line within the address block to avoid multiline greedy capture.
        Zip may appear on the same line or the following line."""
        addr_block = self._extract_address_block(block)
        if not addr_block:
            return "", "", ""
        lines = addr_block.split("\n")
        for idx, line in enumerate(lines):
            m = re.search(r"([A-Za-z][A-Za-z ]+),\s*([A-Z]{2})", line)
            if m:
                city = m.group(1).strip()
                state = m.group(2).strip()
                z = re.search(r"\d{5}", line[m.end():])
                if not z and idx + 1 < len(lines):
                    z = re.search(r"\d{5}", lines[idx + 1])
                return city, state, z.group(0) if z else ""
        return "", "", ""

    def _extract_phone(self, block: str) -> str:
        """Extract first phone number from stop block, excluding None values and extensions."""
        m = re.search(r"^Phone\s+(\+?[\d\s\(\)\-]+)", block, re.I | re.M)
        if m:
            phone = re.sub(r"\s+x\d+.*$", "", m.group(1).strip()).strip()
            return "" if phone.lower() == "none" else phone
        return ""

    def _extract_datetime(self, block: str) -> tuple:
        """Extract (date, time_start, time_end) from 'Scheduled For' or 'Appointment Scheduled For'."""
        a = re.search(
            r"(?:Appointment\s+)?Scheduled\s+For\s*\n"
            r"(?:\w+\s+)?(\d{2}/\d{2}/\d{4})\s*\n"
            r"(?:from\s+(\d{2}:\d{2})\s*-\s*(\d{2}:\d{2})|at\s+(\d{2}:\d{2}))",
            block, re.I
        )
        if a:
            d = a.group(1)
            return (d, a.group(2), a.group(3)) if a.group(2) else (d, a.group(4), a.group(4))
        return "", "", ""

    def extract(self, text: str) -> dict:
        data = {f: "" for f in EXTRACTION_FIELDS}
        if not text:
            return data

        text = self._normalize(text)

        # -------- Broker Info (fixed for Coyote) --------
        data["broker_name"] = "Coyote Logistics, LLC"
        data["broker_address"] = "960 Northpoint Parkway Suite 150"
        data["broker_city"] = "Alpharetta"
        data["broker_state"] = "GA"
        data["broker_zipcode"] = "30005"
        data["broker_phone"] = "877-626-9683"
        data["broker_email"] = "CarrierInvoices@coyote.com"

        # -------- Load Confirmation Number --------
        m = re.search(r"Load\s+(\d{7,9})", text, re.I)
        if m:
            data["loadConfirmationNumber"] = m.group(1).strip()

        # -------- Total Carrier Pay --------
        m = re.search(r"Total\s+USD\s+\$?([\d,]+\.\d{2})", text, re.I)
        if m:
            data["totalCarrierPay"] = m.group(1).replace(",", "").strip()

        # -------- Carrier and Rep Info — Agreement section --------
        # Markdown TXT structure:
        # ### Agreement
        # Broker Coyote Logistics, LLC
        # Rep Tamaz Bazgadze
        # Phone +1 (423) 385 3805 x2246
        # Carrier
        # GTT Freight Corp     <- carrier name is on the NEXT line after 'Carrier'
        # USDOT 3723304
        ag_m = re.search(r"Agreement\s*\n(.+?)(?:\n#+\s|\Z)", text, re.I | re.S)
        if ag_m:
            ag = ag_m.group(1)
            cn = re.search(r"^Carrier\s*\n([A-Za-z0-9 &\.\-]+)$", ag, re.I | re.M)
            if cn:
                data["carrier_name"] = cn.group(1).strip()
            for pat, key in [
                (r"^USDOT\s+(\d+)$", "carrier_usdot"),
                (r"^Email\s+([\w\.\-]+@[\w\.\-]+\.\w+)$", "carrier_email"),
                (r"^Rep\s+([A-Za-z ]+)$", "broker_rep"),
                (r"^Phone\s+(\+[\d\s\(\)\-x]+)$", "broker_rep_phone"),
            ]:
                m = re.search(pat, ag, re.I | re.M)
                if m:
                    data[key] = m.group(1).strip()

        # -------- Stop Blocks --------
        pickup_idx = 1
        delivery_idx = 1

        for stop_type, block in self._extract_stop_blocks(text):
            facility = self._extract_facility(block)
            address = self._extract_address(block)
            city, state, zipcode = self._extract_city_state_zip(block)
            phone = self._extract_phone(block)
            date_str, t1, t2 = self._extract_datetime(block)
            start_dt = self._parse_datetime(date_str, t1)
            end_dt = self._parse_datetime(date_str, t2)

            if stop_type == "pickup" and pickup_idx <= 3:
                i = pickup_idx
                data.update({
                    f"pickup_facility_{i}": facility, f"pickup_address_{i}": address,
                    f"pickup_city_{i}": city, f"pickup_state_{i}": state,
                    f"pickup_zipcode_{i}": zipcode, f"pickup_phone_{i}": phone,
                    f"pickup_start_datetime_{i}": start_dt, f"pickup_end_datetime_{i}": end_dt,
                })
                pickup_idx += 1

            elif stop_type == "delivery" and delivery_idx <= 3:
                i = delivery_idx
                data.update({
                    f"delivery_facility_{i}": facility, f"delivery_address_{i}": address,
                    f"delivery_city_{i}": city, f"delivery_state_{i}": state,
                    f"delivery_zipcode_{i}": zipcode, f"delivery_phone_{i}": phone,
                    f"delivery_start_datetime_{i}": start_dt, f"delivery_end_datetime_{i}": end_dt,
                })
                delivery_idx += 1

        return data


# ============================================================
# Schema fields
# ============================================================
EXTRACTION_FIELDS = [
    "broker_name", "broker_phone", "broker_email",
    "broker_address", "broker_city", "broker_state", "broker_zipcode",
    "broker_rep", "broker_rep_phone",
    "loadConfirmationNumber", "totalCarrierPay",
    "carrier_name", "carrier_usdot", "carrier_email",
    *[f"{p}_{i}" for p in [
        "pickup_facility", "pickup_address", "pickup_city",
        "pickup_state", "pickup_zipcode", "pickup_phone",
        "pickup_start_datetime", "pickup_end_datetime"
    ] for i in range(1, 4)],
    *[f"{p}_{i}" for p in [
        "delivery_facility", "delivery_address", "delivery_city",
        "delivery_state", "delivery_zipcode", "delivery_phone",
        "delivery_start_datetime", "delivery_end_datetime"
    ] for i in range(1, 4)],
    "processed_at"
]


# ============================================================
# Spark UDF wrapper
# ============================================================
def extract_fields_udf():
    extractor = CYExtractor()

    def _extract(text):
        result = extractor.extract(text)
        result["processed_at"] = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
        return result

    return udf(_extract, MapType(StringType(), StringType()))


# ============================================================
# Main (parameterized)
# ============================================================
def main(p):
    spark = SparkSession.builder.appName("CY Extraction").getOrCreate()
    logger.info("Starting CY extraction process")

    input_path = os.path.join(p["source_path"], "*.txt")
    df = (
        spark.read.format("binaryFile")
        .option("pathGlobFilter", "*.txt")
        .option("recursiveFileLookup", "false")
        .load(input_path)
        .select(col("_metadata.file_path").alias("source_file"), col("content"))
    )

    df = df.withColumn("text", col("content").cast("string")).drop("content")
    logger.info(f"Files detected: {df.count()}")

    extract_udf = extract_fields_udf()
    df = df.withColumn("extracted", extract_udf(col("text")))

    for field in EXTRACTION_FIELDS:
        df = df.withColumn(field, col("extracted").getItem(field))

    df = df.drop("text", "extracted")

    logger.info(f"Writing {df.count()} records to {p['target_table']}")
    (
        df.write.format("delta")
        .mode("overwrite")
        .option("mergeSchema", "true")
        .saveAsTable(p["target_table"])
    )

    logger.info("CY extraction completed successfully.")


# ============================================================
# CLI entry
# ============================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CY PDF Extraction Parameters")
    parser.add_argument("--source_path")
    parser.add_argument("--target_table")
    args = parser.parse_args()

    params = {"source_path": args.source_path, "target_table": args.target_table}
    main(params)
